import { PredictionServiceClient } from '@google-cloud/aiplatform';
import { Storage } from '@google-cloud/storage';
import { v4 as uuidv4 } from 'uuid';
import dotenv from 'dotenv';

dotenv.config();

// Initialize clients
const vertexClient = new PredictionServiceClient({
    apiEndpoint: `${process.env.VERTEX_AI_LOCATION || 'us-central1'}-aiplatform.googleapis.com`,
});

const storage = new Storage({
    projectId: process.env.GOOGLE_CLOUD_PROJECT_ID,
    keyFilename: process.env.GOOGLE_APPLICATION_CREDENTIALS,
});

const bucket = storage.bucket(process.env.GCS_BUCKET_NAME || 'mirror-ia-images');

/**
 * Professional Image Generation with Vertex AI Imagen 3.0
 * - Generates high-quality edited images
 * - Stores in Google Cloud Storage
 * - Returns public URL with CDN
 * - Tracks usage for billing
 */
export const generateImageProfessional = async (prompt, originalImageBuffer, mimeType = 'image/png') => {
    const projectId = process.env.GOOGLE_CLOUD_PROJECT_ID;
    const location = process.env.VERTEX_AI_LOCATION || 'us-central1';
    const model = 'imagegeneration@006'; // Imagen 3.0

    // Construct endpoint
    const endpoint = `projects/${projectId}/locations/${location}/publishers/google/models/${model}`;

    // Prepare request for image editing
    const instance = {
        prompt: `Professional hairstyle transformation: ${prompt}. CRITICAL: Preserve the person's face, facial features, skin tone, and clothing exactly as in the original image. Only modify the hairstyle. Maintain photorealistic quality and natural lighting.`,
        image: {
            bytesBase64Encoded: originalImageBuffer.toString('base64'),
        },
        parameters: {
            sampleCount: 1,
            aspectRatio: '1:1',
            personGeneration: 'allow_adult', // Allow person editing
            safetySetting: 'block_some',
            language: 'auto',
        },
    };

    const request = {
        endpoint,
        instances: [instance],
    };

    console.log(`🎨 Generating image with Vertex AI Imagen 3.0...`);

    try {
        // Call Vertex AI
        const [response] = await vertexClient.predict(request);

        if (!response.predictions || response.predictions.length === 0) {
            throw new Error('No image generated by Vertex AI');
        }

        const prediction = response.predictions[0];

        // Extract base64 image
        const base64Image = prediction.bytesBase64Encoded;
        if (!base64Image) {
            throw new Error('No image data in response');
        }

        // Convert to buffer
        const imageBuffer = Buffer.from(base64Image, 'base64');

        // Generate unique filename
        const filename = `hairstyle_${uuidv4()}.png`;
        const file = bucket.file(filename);

        // Upload to Cloud Storage
        console.log(`☁️ Uploading to Cloud Storage: ${filename}`);
        await file.save(imageBuffer, {
            metadata: {
                contentType: 'image/png',
                cacheControl: 'public, max-age=31536000', // 1 year cache
            },
            public: true, // Make publicly accessible
        });

        // Get public URL
        const publicUrl = `https://storage.googleapis.com/${bucket.name}/${filename}`;

        console.log(`✅ Image generated and stored: ${publicUrl}`);

        // Return in format compatible with existing mirrorService.js
        return {
            candidates: [{
                content: {
                    parts: [{
                        inlineData: {
                            data: base64Image,
                            mimeType: 'image/png'
                        }
                    }]
                }
            }],
            usageMetadata: {
                promptTokenCount: 0,
                candidatesTokenCount: 0,
                totalTokenCount: 1, // Count as 1 image generation
            },
            // Custom data for tracking
            customData: {
                public_url: publicUrl,
                storage_path: filename,
                model: 'imagen-3.0',
                timestamp: new Date().toISOString(),
            }
        };

    } catch (error) {
        console.error('❌ Vertex AI Error:', error);
        throw new Error(`Image generation failed: ${error.message}`);
    }
};

/**
 * Fallback: Use Gemini with API Key authentication for download
 * (Keep as backup if Vertex AI is not configured)
 */
export const generateImageFallback = async (prompt, originalImageBuffer, mimeType, apiKey) => {
    const { GoogleGenerativeAI } = await import('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(apiKey);

    const model = genAI.getGenerativeModel({
        model: 'gemini-2.0-flash-exp',
        systemInstruction: `You are a professional hairstylist AI. Edit ONLY the hairstyle. Preserve face and clothes.`
    });

    const result = await model.generateContent({
        contents: [{
            role: 'user',
            parts: [
                { text: `Change hairstyle to: ${prompt}. Return JSON: {"edited_image": "URL"}` },
                {
                    inlineData: {
                        data: originalImageBuffer.toString('base64'),
                        mimeType
                    }
                }
            ]
        }],
        generationConfig: {
            responseMimeType: 'application/json'
        }
    });

    const response = await result.response;
    let text = response.text();

    // Parse JSON
    const firstBrace = text.indexOf('{');
    const lastBrace = text.lastIndexOf('}');

    if (firstBrace !== -1 && lastBrace !== -1) {
        const jsonString = text.substring(firstBrace, lastBrace + 1);
        const data = JSON.parse(jsonString);

        if (data.edited_image) {
            // Download with authentication
            const fetch = (await import('node-fetch')).default;
            const imgReq = await fetch(data.edited_image, {
                headers: {
                    'Authorization': `Bearer ${apiKey}`,
                    'X-Goog-Api-Key': apiKey
                }
            });

            if (!imgReq.ok) {
                throw new Error(`Failed to download: ${imgReq.status}`);
            }

            const buffer = Buffer.from(await imgReq.arrayBuffer());

            return {
                candidates: [{
                    content: {
                        parts: [{
                            inlineData: {
                                data: buffer.toString('base64'),
                                mimeType: 'image/png'
                            }
                        }]
                    }
                }],
                usageMetadata: response.usageMetadata
            };
        }
    }

    throw new Error('No valid image URL in response');
};
